fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: channel
  type: STRING
- mode: NULLABLE
  name: adjust_network
  type: STRING
- mode: NULLABLE
  name: install_source
  type: STRING
- mode: NULLABLE
  name: dau
  type: INTEGER
- mode: NULLABLE
  name: new_profiles
  type: INTEGER
- mode: NULLABLE
  name: search_count
  type: INTEGER
- mode: NULLABLE
  name: ad_clicks
  type: INTEGER
